---
- name: Install ETCD
  hosts: etcd_servers
  become: yes
  vars:
    CLUSTER_NAME: "constellation" # TODO: Change this to the actual cluster name
    # ETCD SETTINGS
    ETCD_MAJOR_VERSION: "3"
    ETCD_MINOR_VERSION: "6"
    ETCD_PATCH_VERSION: "11"
    ETCD_VERSION: "v{{ ETCD_MAJOR_VERSION }}.{{ ETCD_MINOR_VERSION }}.{{ ETCD_PATCH_VERSION }}"
    ETCD_DOWNLOAD_URL: "https://github.com/etcd-io/etcd/releases/download"
    ETCD_TAR_FILE: "{{ ETCD_DIRECTORY }}/etcd-{{ ETCD_VERSION }}-linux-amd64.tar.gz"
    ETCD_CLUSTER_NAME: "{{ CLUSTER_NAME }}"
    ETCD_DIRECTORY: "/opt/etcd/{{ ETCD_VERSION }}" # TODO: Change this to the actual etcd directory
    ETCD_PEER_URLS_PORT: "2480"
    ETCD_CLIENT_URLS_PORT: "2479"
    # HAPROXY SETTINGS
    HAPROXY_MAX_CONNECTIONS: "1000"
    HAPROXY_POSTGRES_PORT: "5100"
    HAPROXY_POSTGRES_READONLY_PORT: "5101"
    HAPROXY_STATISTICS_PORT: "9001"
    HAPROXY_DMA_PORT: "9301"
    # POSTGRES SETTINGS
    POSTGRES_VERSION: "18"
    # POSTGRES DIRECTORIES
    POSTGRES_ROOT_DIRECTORY: "/opt/postgres" # TODO: Change this to the actual postgres directory
    POSTGRES_DEFAULT_DIRECTORY: "/var/lib/pgsql/"
    POSTGRES_BIN_DIRECTORY: "/usr/pgsql-{{ POSTGRES_VERSION }}/bin"
    POSTGRES_DATA_DIRECTORY: "{{ POSTGRES_ROOT_DIRECTORY }}/{{ POSTGRES_VERSION }}/data"
    POSTGRES_LOG_DIRECTORY: "{{ POSTGRES_ROOT_DIRECTORY }}/{{ POSTGRES_VERSION }}/log"
    # POSTGRES ADMIN USERS AND PASSWORDS
    POSTGRES_SUPERUSER_USERNAME: "postgres"
    POSTGRES_SUPERUSER_PASSWORD: "postgres" # TODO: Change this to a secure password
    POSTGRES_REPLICATION_USERNAME: "rep_user"
    POSTGRES_REPLICATION_PASSWORD: "postgres" # TODO: Change this to a secure password
    POSTGRES_REWIND_USERNAME: "rep_user"
    POSTGRES_REWIND_PASSWORD: "postgres" # TODO: Change this to a secure password
    # CITUS VERSION
    CITUS_MAJOR_VERSION: "14"
    CITUS_MINOR_VERSION: "0"
    CITUS_PATCH_VERSION: "1"
    CITUS_VERSION: "{{ CITUS_MAJOR_VERSION }}{{ CITUS_MINOR_VERSION }}{{ CITUS_PATCH_VERSION }}"
    # PYTHON
    # PYTHON 3.9 IS DEFAULT for ALMA LINUX 9
    PYTHON_MAJOR_VERSION: "3"
    PYTHON_MINOR_VERSION: "9"
    PYTHON_VERSION: "{{ PYTHON_MAJOR_VERSION }}{{ PYTHON_MINOR_VERSION }}"
    # PATRONI SETTINGS
    PATRONI_CLUSTER_NAME: "{{ CLUSTER_NAME }}"
    PATRONI_CITUS_DB_NAME: "{{ CLUSTER_NAME }}" # TODO: Change this to the actual distributed database name
    # PATRONI VERSION
    PATRONI_MAJOR_VERSION: "4"
    PATRONI_MINOR_VERSION: "1"
    PATRONI_PATCH_VERSION: "3"
    PATRONI_VERSION: "v{{PATRONI_MAJOR_VERSION}}.{{PATRONI_MINOR_VERSION}}.{{PATRONI_PATCH_VERSION}}"
    # PATRONI DIRECTORIES
    PATRONI_DOWNLOAD_URL: "https://github.com/patroni/patroni/archive/refs/tags/{{ PATRONI_VERSION }}.tar.gz"
    PATRONI_DIRECTORY: "/opt/patroni/{{ PATRONI_VERSION }}"
    PATRONI_TAR_FILE: "{{ PATRONI_DIRECTORY }}/patroni-{{ PATRONI_VERSION }}.tar.gz"
    # PATRONI JUMP SERVER
    JUMP_SERVER_IP: "127.0.0.1" # TODO: Change this to the actual jump server IP
  tasks:
    - name: Create etcd group
      group:
        name: etcd
        system: yes
    - name: Create etcd user
      user:
        name: etcd
        group: etcd
        system: yes
        shell: "/sbin/nologin"
    - name: Create etcd data directory
      file:
        path: "{{ ETCD_DIRECTORY }}/data"
        state: directory
        mode: '0755'
        owner: etcd
        group: etcd
        recurse: yes
    - name: Download etcd tarball
      get_url:
        url: "{{ ETCD_DOWNLOAD_URL }}/{{ ETCD_VERSION }}/etcd-{{ ETCD_VERSION }}-linux-amd64.tar.gz"
        dest: "{{ ETCD_TAR_FILE }}"
    - name: Extract etcd tarball
      unarchive:
        src: "{{ ETCD_TAR_FILE }}"
        dest: "{{ ETCD_DIRECTORY }}"
        remote_src: yes
        extra_opts:
          - --strip-components=1
          - --no-same-owner
    - name: Remove etcd tarball after extraction
      file:
        path: "{{ ETCD_TAR_FILE }}"
        state: absent
    - name: Service File Template
      template:
        src: etcd.service.j2
        dest: "/etc/systemd/system/etcd.{{ ETCD_VERSION }}.service"
        owner: etcd
        group: etcd
        mode: '0644'
    - name: Reload systemd to recognize etcd service
      systemd:
        daemon_reload: yes
    - name: Start and enable etcd service
      systemd:
        name: "etcd.{{ ETCD_VERSION }}.service"
        state: started
        enabled: yes
...