---
# Please Ensure SELinux and OS Firewall are disabled
# https://www.haproxy.com/downloads
- name: Install HAProxy RPM Latest
  hosts: all
  become: yes
  var_files:
    - cluster-settings.yml # TODO: Replace with content of cluster-settings.yml
  tasks:
    - name: Install dnf-plugins-core
      ansible.builtin.dnf:
        name: dnf-plugins-core
        state: present
    - name: Import HAProxy GPG key
      ansible.builtin.rpm_key:
        key: https://www.haproxy.com/download/haproxy/HAPROXY-key-community.asc
        state: present
    - name: Add HAProxy repository
      ansible.builtin.yum_repository:
        name: haproxy-performance
        description: HAProxy Performance Repository
        baseurl: https://www.haproxy.com/download/haproxy/performance/rhel/ha33/el9/x86_64
        gpgcheck: yes
        enabled: yes
    - name: Install haproxy-awslc
      ansible.builtin.dnf:
        name: haproxy-awslc
        state: present
    - name: Create haproxy group
      group:
        name: haproxy
        system: yes
    - name: Create haproxy user
      user:
        name: haproxy
        group: haproxy
        system: yes
        shell: "/sbin/nologin"
    - name: Reload systemd to recognize service
      systemd:
        daemon_reload: yes
    - name: Config file template
      template:
        src: haproxy.cfg.j2
        dest: /etc/haproxy/haproxy.cfg
        owner: haproxy
        group: haproxy
        mode: '0644'
    - name: Enable HAProxy service
      systemd:
        name: haproxy
        enabled: yes
        state: started
...