---
- name: Clean Patroni File
  hosts: all
  become: yes
  vars:
    OLD_POSTGRES_VERSION: "16"
    NEW_POSTGRES_VERSION: "17"
    POSTGRES_ROOT_DIR: "/opt/postgres"
    POSTGRES_DEFAULT_DIR: "/var/lib/pgsql"
  tasks:
    - name: Remove Patroni Config
      ansible.builtin.shell: "rm -f /etc/patroni/dev-citus.{{ OLD_POSTGRES_VERSION }}.yml"
    - name: Backup Patroni Config
      ansible.builtin.shell: "cp /etc/patroni/dev-citus.yml /etc/patroni/dev-citus.{{ OLD_POSTGRES_VERSION }}.yml"
    - name: Remove shared_preload_libraries
      ansible.builtin.lineinfile:
        path: "/etc/patroni/dev-citus.{{ OLD_POSTGRES_VERSION }}.yml"
        regexp: 'shared_preload_libraries'
        state: absent
    - name: Remove unix_socket_directories
      ansible.builtin.lineinfile:
        path: "/etc/patroni/dev-citus.{{ OLD_POSTGRES_VERSION }}.yml"
        regexp: 'unix_socket_directories'
        state: absent
    - name: Remove logging_collector
      ansible.builtin.lineinfile:
        path: "/etc/patroni/dev-citus.{{ OLD_POSTGRES_VERSION }}.yml"
        regexp: 'logging_collector'
        state: absent
    - name: Remove log_directory
      ansible.builtin.lineinfile:
        path: "/etc/patroni/dev-citus.{{ OLD_POSTGRES_VERSION }}.yml"
        regexp: 'log_directory'
        state: absent
    - name: Remove log_filename
      ansible.builtin.lineinfile:
        path: "/etc/patroni/dev-citus.{{ OLD_POSTGRES_VERSION }}.yml"
        regexp: 'log_filename'
        state: absent
...