---
- name: debug_test
  hosts: all
  become: yes
  tasks:
    - name: Set Postgres Password
      ansible.builtin.shell: runuser -u postgres -- psql -U postgres -c "ALTER USER postgres WITH PASSWORD 'postgres';"
    - name: Restart Postgres Service
      ansible.builtin.service:
        name: postgresql-16
        state: restarted
...