---
- name: Install Postgres
  hosts: postgres_servers
  become: yes
#  var_files:
#    - cluster-settings.yml # TODO: Replace with content of cluster-settings.yml
  vars:
    CLUSTER_NAME: "constellation_v18" # TODO: Change this to the actual cluster name
    # ETCD SETTINGS
    ETCD_MAJOR_VERSION: "3"
    ETCD_MINOR_VERSION: "6"
    ETCD_PATCH_VERSION: "11"
    ETCD_VERSION: "v{{ ETCD_MAJOR_VERSION }}.{{ ETCD_MINOR_VERSION }}.{{ ETCD_PATCH_VERSION }}"
    ETCD_DOWNLOAD_URL: "https://github.com/etcd-io/etcd/releases/download"
    ETCD_TAR_FILE: "{{ ETCD_DIRECTORY }}/etcd-{{ ETCD_VERSION }}-linux-amd64.tar.gz"
    ETCD_CLUSTER_NAME: "{{ CLUSTER_NAME }}"
    ETCD_DIRECTORY: "/opt/etcd/{{ ETCD_VERSION }}" # TODO: Change this to the actual etcd directory
    ETCD_PEER_URLS_PORT: "2480" # TODO: Change this to the actual peer URLs port
    ETCD_CLIENT_URLS_PORT: "2479" # TODO: Change this to the actual client URLs port
    # HAPROXY SETTINGS
    HAPROXY_MAX_CONNECTIONS: "1000"
    HAPROXY_POSTGRES_PORT: "5100" # TODO: Change this to the actual postgres port
    HAPROXY_POSTGRES_READONLY_PORT: "5101" # TODO: Change this to the actual postgres readonly port
    HAPROXY_STATISTICS_PORT: "9001"
    HAPROXY_DMA_PORT: "9301"
    # POSTGRES SETTINGS
    POSTGRES_VERSION: "18"
    POSTGRES_DEFAULT_PORT: "5433" # TODO: Change this to the actual default port
    # POSTGRES DIRECTORIES
    POSTGRES_ROOT_DIRECTORY: "/opt/postgres" # TODO: Change this to the actual postgres directory
    POSTGRES_DEFAULT_DIRECTORY: "/var/lib/pgsql/"
    POSTGRES_BIN_DIRECTORY: "/usr/pgsql-{{ POSTGRES_VERSION }}/bin"
    POSTGRES_DATA_DIRECTORY: "{{ POSTGRES_ROOT_DIRECTORY }}/{{ POSTGRES_VERSION }}/data"
    POSTGRES_LOG_DIRECTORY: "{{ POSTGRES_ROOT_DIRECTORY }}/{{ POSTGRES_VERSION }}/log"
    # POSTGRES ADMIN USERS AND PASSWORDS
    POSTGRES_SUPERUSER_USERNAME: "postgres"
    POSTGRES_SUPERUSER_PASSWORD: "postgres" # TODO: Change this to a secure password
    POSTGRES_REPLICATION_USERNAME: "rep_user"
    POSTGRES_REPLICATION_PASSWORD: "postgres" # TODO: Change this to a secure password
    POSTGRES_REWIND_USERNAME: "rep_user"
    POSTGRES_REWIND_PASSWORD: "postgres" # TODO: Change this to a secure password
    # CITUS VERSION
    CITUS_MAJOR_VERSION: "14"
    CITUS_MINOR_VERSION: "" # Ignore "0" version
    CITUS_PATCH_VERSION: "1"
    CITUS_VERSION: "{{ CITUS_MAJOR_VERSION }}{{ CITUS_MINOR_VERSION }}{{ CITUS_PATCH_VERSION }}"
    # PYTHON
    # PYTHON 3.9 IS DEFAULT for ALMA LINUX 9
    PYTHON_MAJOR_VERSION: "3"
    PYTHON_MINOR_VERSION: "9"
    PYTHON_VERSION: "{{ PYTHON_MAJOR_VERSION }}{{ PYTHON_MINOR_VERSION }}"
    # PATRONI SETTINGS
    PATRONI_CLUSTER_NAME: "{{ CLUSTER_NAME }}"
    PATRONI_CITUS_DB_NAME: "{{ CLUSTER_NAME }}" # TODO: Change this to the actual distributed database name
    PATRONI_API_PORT: "8009" # TODO: Change this to the actual API port
    # PATRONI VERSION
    PATRONI_MAJOR_VERSION: "4"
    PATRONI_MINOR_VERSION: "1"
    PATRONI_PATCH_VERSION: "3"
    PATRONI_VERSION: "v{{PATRONI_MAJOR_VERSION}}.{{PATRONI_MINOR_VERSION}}.{{PATRONI_PATCH_VERSION}}"
    # PATRONI DIRECTORIES
    PATRONI_DOWNLOAD_URL: "https://github.com/patroni/patroni/archive/refs/tags/{{ PATRONI_VERSION }}.tar.gz"
    PATRONI_DIRECTORY: "/opt/patroni/{{ PATRONI_VERSION }}"
    PATRONI_TAR_FILE: "{{ PATRONI_DIRECTORY }}/patroni-{{ PATRONI_VERSION }}.tar.gz"
    # PATRONI JUMP SERVER
    JUMP_SERVER_IP: "127.0.0.1" # TODO: Change this to the actual jump server IP
  tasks:
    - name: Create postgres group
      group:
        name: postgres
        system: yes
    - name: Create postgres user
      user:
        name: postgres
        group: postgres
        system: yes
        shell: "/sbin/nologin"
    - name: Add Citus Repository For DNF
      ansible.builtin.shell: curl https://install.citusdata.com/community/rpm.sh | bash
    - name: Install PG Cron
      ansible.builtin.dnf:
        name: pg_cron_{{ POSTGRES_VERSION }}
        state: latest
    - name: Install PG Jobmon
      ansible.builtin.dnf:
        name: pg_jobmon_{{ POSTGRES_VERSION }}
        state: latest
    - name: Install PG Partman
      ansible.builtin.dnf:
        name: pg_partman_{{ POSTGRES_VERSION }}
        state: latest
    - name: Install Postgres with Citus extension
      ansible.builtin.dnf:
        name: citus{{ CITUS_VERSION }}_{{ POSTGRES_VERSION }}
        state: latest
        disable_gpg_check: yes # TODO: permanently disable GPG checks -> sudo nano /etc/yum.repos.d/citusdata_community.repo -> set gpgcheck=0
    - name: Initialize system database
      ansible.builtin.shell: sudo runuser -u postgres -- /usr/pgsql-{{POSTGRES_VERSION}}/bin/initdb --pgdata=/var/lib/pgsql/{{POSTGRES_VERSION}}/data -A scram-sha-256 --auth-local=peer
    - name: Create Unix Socket Directory
      ansible.builtin.file:
        path: /var/run/postgresql
        state: directory
        owner: postgres
        group: postgres
        mode: '0744'
    - name: Create Postgres Root Directory
      ansible.builtin.file:
        path: "{{ POSTGRES_ROOT_DIRECTORY }}/{{ POSTGRES_VERSION }}"
        state: directory
        owner: postgres
        group: postgres
        mode: '0744'
    - name: Create Postgres Data Directory
      ansible.builtin.file:
        path: "{{ POSTGRES_DATA_DIRECTORY }}"
        state: directory
        owner: postgres
        group: postgres
        mode: '0750'
    - name: Create Postgres Log Directory
      ansible.builtin.file:
        path: "{{POSTGRES_LOG_DIRECTORY }}"
        state: directory
        owner: postgres
        group: postgres
        mode: '0750'
    - name: Remove New Data Directory if exists
      ansible.builtin.shell: "rm -rf {{ POSTGRES_ROOT_DIRECTORY }}/{{ POSTGRES_VERSION }}/data"
    - name: Copy Postgres Data Directory to New Location
      ansible.builtin.shell: "cp -R {{ POSTGRES_DEFAULT_DIRECTORY }}/{{ POSTGRES_VERSION }}/data {{ POSTGRES_ROOT_DIRECTORY }}/{{ POSTGRES_VERSION }}"
    - name: Remove Old Data Directory
      ansible.builtin.shell: "rm -rf {{ POSTGRES_DEFAULT_DIRECTORY }}/{{ POSTGRES_VERSION }}/data"
    - name: Config pg_hba.conf file template
      template:
        src: pg_hba.conf.j2
        dest: "{{ POSTGRES_DATA_DIRECTORY }}/pg_hba.conf"
        owner: postgres
        group: postgres
        mode: '0750'
    - name: Config postgresql.conf file template
      template:
        src: postgresql.conf.j2
        dest: "{{ POSTGRES_DATA_DIRECTORY }}/postgresql.conf"
        owner: postgres
        group: postgres
        mode: '0750'
    - name: Create Postgres Service Directory
      ansible.builtin.file:
        path: "/etc/systemd/system/postgresql-{{ POSTGRES_VERSION }}.service.d"
        state: directory
        recurse: yes
    - name: Create Postgres Service File
      template:
        src: postgres.service.j2
        dest: "/etc/systemd/system/postgresql-{{ POSTGRES_VERSION }}.service.d/override.conf"
        owner: postgres
        group: postgres
        mode: '0750'
    - name: Reload Service Config
      ansible.builtin.shell: "systemctl daemon-reload"
    - name: Install Self Signed Cert - Step 1
      ansible.builtin.shell:
        chdir: "{{ POSTGRES_DATA_DIRECTORY }}"
        cmd: "openssl genrsa -out rootCA.key 2048"
    - name: Install Self Signed Cert - Step 2
      ansible.builtin.shell:
        chdir: "{{ POSTGRES_DATA_DIRECTORY }}"
        cmd: "openssl req -x509 -new -key rootCA.key -days 10000 -out rootCA.crt -batch"
    - name: Install Self Signed Cert - Step 3
      ansible.builtin.shell:
        chdir: "{{ POSTGRES_DATA_DIRECTORY }}"
        cmd: "openssl genrsa -out server.key 2048"
    - name: Install Self Signed Cert - Step 4
      ansible.builtin.shell:
        chdir: "{{ POSTGRES_DATA_DIRECTORY }}"
        cmd: "openssl req -new -key server.key -out server.csr -batch"
    - name: Install Self Signed Cert - Step 5
      ansible.builtin.shell:
        chdir: "{{ POSTGRES_DATA_DIRECTORY }}"
        cmd: "openssl x509 -req -in server.csr -CA rootCA.crt -CAkey rootCA.key -CAcreateserial -out server.crt -days 1000"
    - name: Install Self Signed Cert - Step 6
      ansible.builtin.shell:
        chdir: "{{ POSTGRES_DATA_DIRECTORY }}"
        cmd: "chmod 600 server.key"
    - name: Install Self Signed Cert - Step 7
      ansible.builtin.shell:
        chdir: "{{ POSTGRES_DATA_DIRECTORY }}"
        cmd: "chmod 600 server.crt"
    - name: Fix Data Directory Ownership
      ansible.builtin.shell:
        chdir: "{{ POSTGRES_DATA_DIRECTORY }}"
        cmd: "chown -R postgres:postgres {{ POSTGRES_DATA_DIRECTORY }}"
    - name: Enable And Start Postgres Service
      ansible.builtin.service:
        name: postgresql-{{ POSTGRES_VERSION }}
        enabled: yes
        state: started
    - name: Set Postgres Password
      ansible.builtin.shell: runuser -u postgres -- psql -h localhost -p {{ POSTGRES_DEFAULT_PORT }} -U postgres -c "ALTER USER postgres WITH PASSWORD '{{ POSTGRES_SUPERUSER_PASSWORD }}';"
    - name: Set Postgres Replication User Password
      ansible.builtin.shell: runuser -u postgres -- psql -h localhost -p {{ POSTGRES_DEFAULT_PORT }} -U postgres -c "CREATE USER {{ POSTGRES_REPLICATION_USERNAME }} WITH REPLICATION PASSWORD '{{ POSTGRES_REPLICATION_PASSWORD }}';"
    # TODO: Uncomment the following task if Rewind user is different from Replication user
    #    - name: Set Postgres Rewind User Password
    #      ansible.builtin.shell: runuser -u postgres -- psql -U postgres -c "CREATE USER {{ POSTGRES_REWIND_USERNAME }} WITH REPLICATION PASSWORD '{{ POSTGRES_REWIND_PASSWORD }}';"
    - name: Create Distributed DB managed by Patroni
      ansible.builtin.shell: runuser -u postgres -- psql -h localhost -p {{ POSTGRES_DEFAULT_PORT }} -U postgres -c "CREATE DATABASE {{ PATRONI_CITUS_DB_NAME }};"
    - name: Create Citus Extension
      ansible.builtin.shell: runuser -u postgres -- psql -h localhost -p {{ POSTGRES_DEFAULT_PORT }} -U postgres -d {{ PATRONI_CITUS_DB_NAME }} -c "CREATE EXTENSION citus;"
    - name: Disable And Stop Postgres Service
      ansible.builtin.service: # STOP SERVICE - Patroni will manage it
        name: postgresql-{{ POSTGRES_VERSION }}
        enabled: no
        state: stopped

######################################################################################
# IMPORTANT!!! STARTING FROM VERSION 3 PATRONI SET ALL THIS FOR YOU. DON'T RUN IT !!!
######################################################################################
# TODO:
# Register the hostname that future workers will use to connect
# to the coordinator node.
#
# You'll need to change the example, 'coord.example.com',
# to match the actual hostname

# sudo -i -u postgres psql -c "SELECT citus_set_coordinator_host('coord.example.com', {{ POSTGRES_DEFAULT_PORT }});"

# Add the worker nodes.
#
# Similarly, you'll need to change 'worker-101' and 'worker-102' to the
# actual hostnames

# sudo -i -u postgres psql -c "SELECT * from citus_add_node('worker-101', { POSTGRES_DEFAULT_PORT }});"
# sudo -i -u postgres psql -c "SELECT * from citus_add_node('worker-102', { POSTGRES_DEFAULT_PORT }});"

# CHECK INSTALL
# sudo -i -u postgres psql -c "SELECT * FROM citus_get_active_worker_nodes();"
...
